### PR TITLE
AddingPowerSupport_CI/Testing

### PR DESCRIPTION
**Pull request by santosh653**
Adding power support ppc64le with Continues Integration/testing so that code remains architecture independent.

This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing.

The build is successful on both arch: amd64/ppc64le.

Please let me know if you need any further details.

Thank You !!

### CODE REVIEW

**Comment by sebastinas** [comment]
FYI: We are currently thinking of converting the CI to Github Actions.

**Comment by santosh653** [comment]
ok, Are there any further queries on this PR? Is this PR is getting merged?

**Comment by sebastinas** [comment]
Unless this can be done with Github Actions as well, we can't. See f37892b5dad3e1171a69024a3bf9bb3036dfc68b.

**Comment by sebastinas** [comment]
Closing this PR for now because it is not actionable.

**Pull request closed without merging**
